version: '3'

services:
  classroom:
    build: ../../../../
    restart: unless-stopped
    command: yarn dev
    ports:
      - '3001:3001'
    volumes:
      - ../../../../:/home/node/app
    env_file:
      - ../../environment/.env
    networks:
      - net
      - pgadmin

networks:
  pgadmin:
  net:
    driver: bridge

volumes:
  classroom_node_modules:
