kind: Deployment
apiVersion: apps/v1
metadata:
  name: server-pgadmin
  labels:
    app: server-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-pgadmin
  template:
    metadata:
      labels:
        app: server-pgadmin
    spec:
      containers:
        - name: server-pgadmin
          image: 'dpage/pgadmin4'
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: server-env
          volumeMounts:
            - name: server-pgadmin-volume
              mountPath: /var/lib/pgadmin4
      volumes:
        - name: server-pgadmin-volume
          persistentVolumeClaim:
            claimName: server-pgadmin-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: server-pgadmin
  name: server-pgadmin
spec:
  selector:
    app: server-pgadmin
  ports:
    - port: 80
      nodePort: 30543
  type: NodePort
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: server-pgadmin-volume
  labels:
    app: server-pgadmin
    type: local
spec:
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/pgadmin4
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=5050
    - nobrl
    - cache=none
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: server-pgadmin-claim
  labels:
    app: server-pgadmin
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
