version: '3'

services:
  postgres:
    image: 'postgres:14.4-alpine'
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/var/lib/postgresql
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - net
      - pgadmin

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '16543:80'
    depends_on:
      - postgres
    networks:
      - pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  zookeeper:
    image: 'bitnami/zookeeper:3'
    restart: unless-stopped
    ports:
      - '2181:2181'
      - '8080:8080'
    volumes:
      - 'zookeeper_data:/bitnami'
    env_file:
      - .env
    networks:
      - net
    depends_on:
      - postgres

  kafka:
    image: 'bitnami/kafka:3'
    restart: unless-stopped
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    env_file:
      - .env
    depends_on:
      - postgres
      - zookeeper
    networks:
      - net

networks:
  pgadmin:
  net:
    driver: bridge

volumes:
  pgadmin_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  postgresql_data:
    driver: local
