version: '3'

services:
  server-auth:
    build: ../packages/auth
    restart: unless-stopped
    command: yarn dev
    ports:
      - '3001:3001'
    volumes:
      - ../packages/auth:/home/node/app
    env_file:
      - ../packages/auth/src/infra/environment/.env
    networks:
      - net
      - pgadmin

networks:
  pgadmin:
  net:
    driver: bridge

volumes:
  auth_node_modules:
